version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - aifalabs-network

  aifalabs-agent:
    build:
      context: .
    image: aifalabs-agent
    pull_policy: never
    container_name: aifalabs-agent
    ports:
      - "7002:7002"
    volumes:
      - ./config:/app/config
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - aifalabs-network

networks:
  aifalabs-network:
    driver: bridge

volumes:
  postgres_data: